### ISSUE TITLE
minikube as root and which minikube to install

### ISSUE THREAD

**Issue by liviozanol** [eox-dev/minikube-wsl2#1]
Hello!

Tried to run minikube as root but got the below message:
```
sudo minikube start --vm-driver=docker
😄  minikube v1.24.0 on Ubuntu 20.04
✨  Using the docker driver based on user configuration
🛑  The "docker" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
```
So, maybe step ```sudo usermod -aG docker $USER``` should be mandatory? Or a better explanation?

Also, on step 5, I think would be better to specify that you need to install the Linux version, not windows.

Thanks in advance!

**Comment by cheslijones** [comment]
Thanks, those are all great points. I've updated accordingly.
